# -*- coding: utf-8 -*-
"""20514 정다우_6~10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MEHz2hBae-bcFEr2XcGwDK9eAZc6tjR6

##page6
"""

hight = int(input("삼각형 높이: "))
down = int(input("삼각형 밑변: "))
area = (hight * down) / 2
print("삼각형의 면적: ", area)

kg = float(input("킬로그램(kg) 입력: "))
pound = kg * 2.2046
print(kg, "kg은", pound, "파운드입니다.")

"""##page7"""

print(5+2)
print(5-2)
print(5*2)
print(5/2)
print(5**2)
print(5//2)
print(5%2)

x = 10 % 3
print(x)
y=7 // 3
print(y)

a = 10
b = 20
c = a + b * 10 - 5 / 5
print(c)

x = 2 ** 3
print(x)

y = 10 ** 4
print(y)

hello = "안녕 " * 5
print(hello)

s1 = "대한민국"
s2 = " 만세!"
print(s1 + s2)
print(s1 * 5)

print("korea" + str(2021))
print(10 + int("22"))
print(10 + int(22.5))
print(10 + int(float(22.5)))
#print("korea" + 2021)

"""##page8"""

x = 10
x += 20   
print(x)

a = 5
a = a + 1
print(a)

a = 5
a += 1
print(a)

a -= 5
print(a)

a *= 2
print(a)

x = 3
y = 5
x *= x + y 
print(x)

"""##page9"""

cost = int(input("투입한 돈: "))
rate = int(input("물건 값"))
change = cost - rate

if change > 0:
    print("거스름돈: ", change)
    print("500원 동전의 개수: ", change // 500)
    print("100원 동전의 개수: ", (change % 500) // 100)

if 3 < 5 :
    print("Hello World")

if 3 > 5:
    print("Hello World")

age = int(input("몇살입니까? "))
if age < 20:
    print("학생입니다.")

age = 15
if age < 20:
    print("학생입니다.")
print("안녕히가세요.")

age = 20
if age < 20:
    print("학생입니다.")
print("안녕히가세요.")

print(3 == 5)
print(3 != 5)
print(3 < 5)

x = 4
print(1 < x < 5)

#print(3 => 5)

num = int(input("숫자 입력: "))
if num == 5:
    print("5 이다.")
elif num > 5:
    print("5 보다 크다.")
else:
    print("5 보다 작다.")

country = "Korea"
if country == "Korea":
    print("한국")

age = int(input("몇살입니까? "))
if age < 20:
    print("학생입니다.")
else:
    print("성인입니다.")

num = int(input("숫자 입력: "))
if num%2 == 0:
    print("짝수 입니다.")
else:
    print("홀수 입니다.")

num = int(input("정수 입력: "))
if num%5 == 0:
    print("5의 배수 입니다.")
else:
    print("5의 배수가 아닙니다.")

password = input("암호 입력: ")
if password == "암호":
    print("암호이다.")
else:
    print("암호가 아니다.")

fir = int(input("첫번째 숫자 입력: "))
sec = int(input("첫번째 숫자 입력: "))
if fir <= sec:
    print(sec - fir)
else:
    print(fir - sec)

when = int(input("1(주간 근무) 또는 2(야간근무)를 입력해 주세요: "))
time = int(input("근무시간을 입력해 주세요: "))

if when == 1:
    print(time, "시간 동안 일한 주간 급여는", time * 9500, "원 입니다.")
else:
    print(time, "시간 동안 일한 야간 급여는", int(time * 9500 * 1.5), "원 입니다.")



name = input("이름을 입력하시오: ")
time = int(input("일주일간 일한 시간을 입력하세요: "))
over = time - 40

if time >= 40:
    print("초과 시간: ", over)
    print(name, "님의 주급은", int((40 * 12000) + (over * 12000 * 1.5)), "원 입니다.")
else:
    print(name, "님의 주급은", time * 12000, "원 입니다.")

print((3 == 3) and (4 != 3))
print((3 == 3) or (4 != 3))
print(not(4 != 3))